---
## secrets ##
# Use this file to store secrets like usernames and passwords. #
# Learn more at https://www.home-assistant.io/docs/configuration/secrets/

# DEVICES #

# antu_alarm_panel
home_alarm_code: 9999

# air_quality_sensor
sensorapiurl: http://andaaaaaa.com

# INTEGRATIONS #

# deepstack
deep_ip: 10.0.0.0
deep_port: 5100
deep_file_folder: '/config/recognition/snapshots'
deep_faces_folder: '/config/recognition/faces/'
api_key: '=98905528-1144-49f0-9379-e8fc576982b7'

# Eufy
eufy_email: hahaha@gmail.com
eufy_pass: password

# Home Assistant
latitude: 11.111
longitude: 2.0
internal_url: http://10.0.0.1:8123
external_url: https://haha.com

# http
ssl_certificate: /ssl/fullchain.pem
ssl_key: /ssl/privkey.pem

# Database
db_url: mysql://hassio_db:asdad@10.0.0.10:3307/hassio_db?charset=utf8mb4
