---
## remote_ikea ##
# Automations for the Ikea Remote

automation:

  # Middle Button
  - id: 'devices_remote_ikea_middle'
    alias: Devices - remote_ikea - Middle
    trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: tradfri_remote_control
        event: 1002
    condition: []
    action:
    - if:
      - condition: device
        type: is_on
        entity_id: switch.aqara_interruptor
        domain: switch
      then:
      - type: turn_on
        entity_id: light.innr_gu10_1
        domain: light
        brightness_pct: 100
        flash: short
      - type: turn_on
        entity_id: light.innr_gu10_2
        domain: light
        brightness_pct: 100
        flash: short
      - type: turn_on
        entity_id: light.innr_gu10_3
        domain: light
        brightness_pct: 100
        flash: short
      - type: turn_off
        entity_id: switch.aqara_interruptor
        domain: switch
      else:
      - type: turn_on
        entity_id: switch.aqara_interruptor
        domain: switch
      - type: turn_on
        entity_id: light.innr_gu10_1
        domain: light
        brightness_pct: 100
        flash: short
    mode: single

  # Right Button
  - id: 'devices_remote_ikea_right'
    alias: Devices - remote_ikea - Right
    trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: tradfri_remote_control
        event: 5002
    action:
    - if:
      - condition: device
        type: is_on
        entity_id: switch.aqara_interruptor
        domain: switch
      then:
      - type: turn_off
        entity_id: light.innr_gu10_2
        domain: light
      - type: turn_off
        entity_id: light.innr_gu10_3
        domain: light
      - type: turn_on
        entity_id: light.innr_gu10_1
        domain: light
        flash: short
        brightness_pct: 5
      else:
      - type: turn_off
        entity_id: light.innr_gu10_2
        domain: light
      - type: turn_off
        entity_id: light.innr_gu10_3
        domain: light
      - type: turn_on
        entity_id: light.innr_gu10_1
        domain: light
        brightness_pct: 5
        flash: short
    mode: single

  # Left Button
  - id: 'devices_remote_ikea_left'
    alias: Devices - remote_ikea - Left
    trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: tradfri_remote_control
        event: 4002
    action:
    - if:
      - condition: device
        type: is_on
        entity_id: switch.aqara_interruptor
        domain: switch
      then:
      - type: turn_off
        entity_id: light.innr_gu10_2
        domain: light
      - type: turn_off
        entity_id: light.innr_gu10_3
        domain: light
      - type: turn_on
        entity_id: light.innr_gu10_1
        domain: light
        flash: short
        brightness_pct: 100
      else:
      - type: turn_off
        entity_id: light.innr_gu10_2
        domain: light
      - type: turn_off
        entity_id: light.innr_gu10_3
        domain: light
      - type: turn_on
        entity_id: light.innr_gu10_1
        domain: light
        brightness_pct: 100
        flash: short
    mode: single

  # Upper Button
  - id: 'devices_remote_ikea_up'
    alias: Devices - remote_ikea - Up
    trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: tradfri_remote_control
        event: 2002
    condition:
    - condition: device
      type: is_on
      entity_id: switch.aqara_interruptor
      domain: switch
    action:
      domain: light
      entity_id: light.menjador
      type: brightness_increase
    mode: single
