---
## system_db ##
# Redirect output to Synology NAS Maria DB
recorder:
  db_url: !secret db_url
  purge_keep_days: 730

sensor:
# MariaDB Size Sensor
  - platform: sql
    db_url: !secret db_url
    queries:
      - name: 'DataBase size'
        query: 'SELECT table_schema "database", Round(Sum(data_length + index_length) / 1024 / 1024 / 1024, 2) "value" FROM information_schema.tables WHERE table_schema="hassio_db" GROUP BY table_schema;'
        column: 'value'
        unit_of_measurement: GB
